### ISSUE TITLE
Programación de videojuegos en Rust usando ECS

### ISSUE THREAD

**Issue by beagleknight** [BcnRust/talks#10]
# Title / Título

Programación de videojuegos en Rust usando ECS

## Details / Detalles

Rust es un lenguaje ideal para la [programación de videojuegos](http://arewegameyet.com/) y el ecosistema está madurando día a día. Este año he empezado a aprender Rust y me he topado con un [tutorial](https://tomassedovic.github.io/roguelike-tutorial/index.html) donde se implementaba un _roguelike_. El tutorial es un port de otro que usaba Python y utiliza la programación orientada a objetos para su implementación.

Tras completar el tutorial empecé a desarrollar el mismo juego usando la librería [specs](https://github.com/slide-rs/specs). Esta librería implementa el patrón Entity - Component- System (ECS) y se aprovecha de la capacidad de Rust para ejecutar código en paralelo. 
En esta charla explicaré mi aventura aprendiendo Rust y ECS simultáneamente. Aunque la programación orientada a objetos es útil para programar videojuegos no es las más eficiente ni extensible. Usando componentes y sistemas podemos representar la misma lógica del videojuego y trabajar con estructuras de datos más accesibles.

## Speaker info / Información sobre el ponente

¡Hola! Mi nombre es David y me gustan los perros, videojuegos y la programación. Actualmente estoy trabajando en Codegram y hace unos meses empecé a aprender Rust en mis horas libres y hasta ahora me encanta! 🦀
También programo videojuegos (a veces) y he participado en algunas GameJAM. Es la primera vez que intento hacer alguna cosa con Rust y videojuegos pero todavía no tengo la soltura necesaria para usarlo en alguna JAM 😅 

## Level / Nivel

- [x] Beginner / Iniciación
- [ ] Intermediate / intermedio
- [ ] Advanced / Avanzado

## Duration / Duración

- La duración de la charla será de entre 20 y 30 minutos.
- Si hay tiempo me gustaría hacer alguna demo de live coding o enseñar el juego en funcionamiento 😄 Entre 5 y 10 minutos sería suficiente.

**Comment by piny4man** [comment]
Hola @beagleknight , como llevas esta charla ? Te animarias a hacer un meetup a final de Setiembre o es demasiado pronto ? 🤔

**Comment by beagleknight** [comment]
Hola @alberss !
La verdad es que ahora mismo estoy preparando otra charla para la primera semana de octubre así que realmente lo veo un poco justo 😅 .
¿Que os parece para finales de Octubre?

**Comment by robertohuertasm** [comment]
Perfecto David! 👍

**Comment by piny4man** [comment]
Sin problema @beagleknight ! En Octubre va genial tambien 😁
