### ISSUE TITLE
what about hands-on instead of talks?

### ISSUE THREAD

**Issue by newlog** [BcnRust/talks#2]
Hi there,

I've been waiting for so long for a Rust meetup in Barcelona!

I really think that even more than talks, what people (like me) would benefit from would be trainings and projects completely hands-on. Given that Rust has a really steep learning curve, you can talk about anything you want, but what's really needed is people hand holding others and helping them building some cool projects.

Obviously, this takes more time than just talks.

As I see, it would be awesome to have a hackathon-kinda event during a couple of weeks (weekends?) where you set an objective (let's build X) and then spend 10 hours to do so, going through many of the pain points that Rust has.

That way you'd engage people way more, won't leave them 100% on their own after a talk and that will, eventually, pay off, having that people give talks once they are ready.

Just my $.02

**Comment by robertohuertasm** [comment]
Hi @newlog, 

indeed we're also opened to the idea of workshops, hackatons and the like. We really appreciate your idea and we'll be very happy to talk with you about how can we approach this (maybe in our first meetup! 😉). In my mind, this kind of "long" event requires too much implication and free time from people, and usually I think about people with family obligations, for example. Nevertheless, I think is a 👍 so we'll absolutely discuss about how we could organise something that can make everyone happy.

Thanks for opening this issue! ❤️

**Comment by newlog** [comment]
Hey,

I totally get it. Bear in mind, I'm not talking about big projects. Look at this, for reference:

- https://github.com/newlog/rust_projects/tree/master/skydiving

It's just some simple code that parses a website, downloads photos and saves them as files.

Man, that was a real pain in the ass to develop. And it's only like 5 files with 50 lines of code each. However, for someone to be able to write that, they need to understand a little bit about ownership, matching, project structure, how to pass (string!) parameters up and down and learn about external libraries.

Savvy people underestimate how difficult it is to develop something as simple as that for someone new to the language.

Unfortunately I can only give ideas because that first project was so "hard" that I lacked the energy/time to continue with Rust, so I'm far from proficient, but I'd like to learn :)

Let's keep talking!

**Comment by robertohuertasm** [comment]
@newlog, let's see how we can materialise something like this. I think you have a valid point!

**Comment by robertohuertasm** [comment]
@newlog stay tuned, we're preparing a series of workshops!

**Comment by robertohuertasm** [comment]
@newlog I'll close this as we've captured already the message. Indeed in our last meeting we had some sort of hands-on with Webassembly 😉
