### ISSUE TITLE
ragent: a Nagios compatible monitoring agent in Rust

### ISSUE THREAD

**Issue by alexpdp7** [BcnRust/talks#4]
# Title / Título

ragent: a Nagios compatible monitoring agent in Rust

## Details / Detalles

Si andáis faltos de ponentes, si queréis podría dar alguna charlilla sobre:

https://github.com/alexpdp7/ragent

, que es un software de monitorización que hice para mi infraestructura personal. Dependiendo del interés podría comentar:

* El sistema cutre que me he montado para hacer paquetes para distros (de momento soporto CentOS 7 en x86_64 y Debian Stretch en x86_64 y ARM de Raspberry Pi).
* Implementar un mini servidor web con Hyper que sirve una API JSON
* Interacción con nix para sacar info del sistema, process para interactuar con systemd, etc.

No creo que haya nada especialmente interesante, pero como relleno o por intentar animar a la gente podría servir. Si se os ocurre cualquier otra cosa puedo planteármelo.

También puede ser algo tipo "tenía una necesidad y decidí usarla para aprender un poco más de Rust en vez de hacer ejercicios abstractos".

La charla puede ser en castellano, catalán o inglés, en ese orden de preferencia.

## Speaker info / Información sobre el ponente

Trabajo desarrollando software; Java/Python en entornos web, últimamente con bastantes temas de devops (Ansible/Puppet/Salt/AWS). Rust me atrajo desde el principio por la promesa de un lenguaje de alto rendimiento, sin ser el campo de minas de C/C++, sin el GC de Java (y más cercano a la plataforma), con tipado estático y con sólidos fundamentos teóricos (sum types, etc.).

## Level / Nivel

- [x] Beginner / Iniciación

## Duration / Duración

A concretar dependiendo de lo que pueda interesar, pero en general no creo que dé el tema para mucho más que 30m.

...

Por cierto, vivo tres semanas en Madrid, una en Barcelona, así que tendría que concretar fecha con algo de antelación.

**Comment by robertohuertasm** [comment]
@alexpdp7 muchísimas gracias por tu propuesta! Creo que puede ser interesante, sobre todo desde la perspectiva de alguien que se ha acercado al lenguaje desde 0 y ha creado una herramienta. Se puede hablar, además de los detalles implementativos, de cuál ha sido la experiencia de aprendizaje, impresiones que has tenido...

En fin, que muchas gracias porque sí que nos faltan ponentes :wink: Déjame ver cómo podemos preparar el próximo evento y si podemos encontrar alguien más que quiera hablar. Si no, la opción sería preparar algo por mi parte para tener un evento de 1 hora aproximadamente. Tengo un par de ideas que creo que podrían resultar.

Estamos en contacto para cuadrar fechas para cuando vengas a Barcelona!!

**Comment by alexpdp7** [comment]
Genial. De hecho estaré hasta el domingo por aquí, pero un poco justo. También creo que estaré ~26-~30, pero creo que son malas fechas. Supongo que ya la siguiente será la semana del 14, 21 o 28. Te pego un toque por el issue (u otro mecanismo si prefieres) cuando lo tenga claro.

Como estaba algo insomne me he hecho un esquema rápido a muy alto nivel de lo que podría comentar:

https://nextcloud.pdp7.net/nextcloud/index.php/s/wAqHXimrBwBTtfb

Cuando encuentre un rato haré un par de pruebas para ver duración y tal. En realidad si me pusiese a enseñar cosas concretas (código, etc.), hacer alguna demo o entrar en profundidad sobre algún tema (lo del empaquetado, igual) podría alargarme bastante, pero no sé yo.

Si tenéis ponientes más potables ya iré de oyente :-p

**Comment by robertohuertasm** [comment]
Imagino que de realizar un meetup sería de cara a finales de enero, porque ahora ya viene navidad y la gente no está muy por la labor. ¿Cómo lo verías?

**Comment by alexpdp7** [comment]
Sí, perfecto. Yo en cuanto tenga fechas te digo algo, y si coincide perfecto!

**Comment by robertohuertasm** [comment]
Bien! Coincidirá seguro porque por eso no habrá problema y nos adaptaremos! :wink:

**Comment by alexpdp7** [comment]
Buenas Roberto!

Sorry que tengo un poco de ajetreo últimamente. Andaré por Barna del 21-25 de enero aprox.

Si os va bien, os confirmo cuando lo tenga todo atado (e.g. AVE comprado), no sé si hay plazo para organizar todo... Creo que lo podré tener todo bien preparado para entonces.

Si no, ya os digo para la próxima, que este mes he tenido más incertidumbre de lo habitual planificando viajes.

Saludos,

Álex

**Comment by robertohuertasm** [comment]
Alex, pues creo que sería genial si pudieras confirmar la fecha concreta para poder organizarlo, porque tenemos poco margen. Sería bueno quizás si puediera ser el jueves 24. ¡Ya me dirás y vamos preparando todo!

**Comment by alexpdp7** [comment]
Buenas,

Si no tengo imprevistos, el 24 me va bien. Estaré toda la semana así que si hay cambios supongo que me podría adaptar.

A prepararme!

Saludos,

Álex

**Comment by robertohuertasm** [comment]
Anoto el 24 sobre las 19 entonces. Lo voy moviendo ya!

**Comment by robertohuertasm** [comment]
Alex, ¿tienes alguna foto tuya por ahí tipo avatar de Twitter o algo? Es para hacer el cartel del evento 😉

**Comment by alexpdp7** [comment]
Mi pareja dice que parezco un pederasta en esta foto:

https://careers.nttcom.ms/wp-content/uploads/2017/07/alejandro-800x800.jpg

, pero si buscas un mugshot supongo que es lo más potable que tengo.

**Comment by robertohuertasm** [comment]
Jajaja! 😂  ¡Me parece perfecta! ¡Muchísimas gracias Álex!

**Comment by robertohuertasm** [comment]
Por cierto, tienes cuenta de Twitter? Es para mencionarte cuando anuncie el evento

**Comment by alexpdp7** [comment]
Puedes usar @koalillo

**Comment by robertohuertasm** [comment]
Álex!! Qué no tengo tu apellido!! 😱

**Comment by alexpdp7** [comment]
Jejeje, Córcoles

**Comment by robertohuertasm** [comment]
Muchas gracias! Lo había intuído por el dominio de tu web pero me faltaba el acento! 😜
