### ISSUE TITLE
Serverless Rust

### ISSUE THREAD

**Issue by robertohuertasm** [BcnRust/talks#5]
# Title / Título
Serverless Rust

## Details / Detalles
This will be a hands-on talk where we'll build an AWS Lambda and an Azure Function.

## Speaker info / Información sobre el ponente
Roberto Huertas @robertohuertasm 

## Level / Nivel

- [x] Beginner / Iniciación

## Duration / Duración
40 mins

**Comment by carlosb1** [comment]
https://github.com/carlosb1/examples-rust/tree/master/examples_aws_lambda2 <- I did for use cases (I need clean code yet) but if @robertohuertasm  help me for azure, It can be a presentation how to use serverless for:
- scrapping
- rest service
and other ideas...

**Comment by robertohuertasm** [comment]
You can find some examples and blog posts I did regarding `AWS Lambda` ([GitHub](https://github.com/robertohuertasm/aws-lambda-rust), [Blog](https://robertohuertas.com/2018/12/02/aws-lambda-rust/)) and `Azure Functions`  ([GitHub](https://github.com/robertohuertasm/azure-function-rust), [Blog](https://robertohuertas.com/2018/12/22/azure-function-rust/)).

Take into account these were written in last year December so may be a little bit outdated.

**Comment by carlosb1** [comment]
https://docs.google.com/presentation/d/1DmCnT_SHcHoZVIYoLroutGL8ihK4KpeO/edit#slide=id.p1 <- I did a first slides for this presentation. I will do a review and decide a date...
