### ISSUE TITLE
Rust in iOS and Android

### ISSUE THREAD

**Issue by robertohuertasm** [BcnRust/talks#6]
# Title / Título

Rust in iOS and Android

## Details / Detalles

An introduction to learn how to use Rust in iOS and Android.

## Speaker info / Información sobre el ponente

Roberto Huertas @robertohuertasm 

## Level / Nivel

- [x] Beginner / Iniciación

## Duration / Duración

40 mins

**Comment by carlosb1** [comment]
@robertohuertasm  I was checking code, and it doesn't exist any  "mature" wrapper android-rust. It means, for any possible use case (for example copy android camera frames to jni and render), it is necessary to do it yourself in C++.
https://github.com/rust-windowing/android-rs-glue <- It seems to have only operations to load assets and not more...
https://github.com/dobkeratops/android_rust_gl <- It created a c++ endpoint to call opengl operations...
What does it mean? Currently, for any tutorial about this topic, It will be necessary to do "painful" code in C++ (if my presumptions are correct)

**Comment by carlosb1** [comment]
https://github.com/carlosb1/examples-rust/tree/master/android_example <- I started an example with jni  to pass parameters
